### ISSUE TITLE
Like on Spotify

### ISSUE THREAD

**Issue by neptalu0** [jareddantis-bots/blanco-bot#33]
new issue! pressing said button shows this

![IMG_20230909_181942](https://github.com/jareddantis-bots/blanco-bot/assets/43881378/000ce65d-4b13-4f3f-9d15-245f3f2de67f)

**Comment by jareddantis** [comment]
A 403 error hints at incorrect or insufficient credentials. Are these keys still in development mode by any chance?

**Comment by neptalu0** [comment]
oh yeah the issue lies in keys being in development mode. it work when i switched to the dev account it was created. thanks
