### ISSUE TITLE
Feature request: bumps

### ISSUE THREAD

**Issue by holedaemon** [jareddantis-bots/blanco-bot#55]
Howdy, my friends and I have been using Blanco for a while now. Overall it's been a pretty slick experience, thanks for your work on it. It's much appreciated!

Something we've wanted to see in a music bot for a long time now is the ability to play bumps between songs. The idea is to have a list of user-created bumps that the bot can choose from to play once a song ends and at least N minutes have passed. Originally, the intention was to fork and implement this feature in that, which we may still end up doing, but I first wanted to inquire and see if this possibly something that could be added upstream. I'm totally willing to work on it, if you're willing to have it. I also get that this is a really niche feature, so if not no worries.

Thanks

**Comment by jareddantis** [comment]
Hi @holedaemon, thank you for your kind words.

Bumps are a cool idea! Unfortunately I don't have as much time to work on personal projects like Blanco as I used to, so I'm afraid I can't implement this myself, but feel free to fork and open a PR. Fair warning though - I now realize Blanco's architecture is not the cleanest and I am planning to do a rewrite sometime later this year.

I imagine you will have to augment Blanco's `on_track_end` handler (`utils/blanco.py`) or the queue manager (`cogs/player/queue.py`) to insert interstitials between queue items.

**Comment by jareddantis** [comment]
Now in Release 0.5.7. Thanks again :)
